# Generated by Django 4.1.3 on 2023-12-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('キャラクター', 'キャラクター'), ('企業・団体', '企業・団体'), ('種族', '種族'), ('その他', 'その他')], max_length=100)),
            ],
        ),
    ]
