# Generated by Django 4.1.3 on 2023-12-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='member',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
