# Generated by Django 4.1.3 on 2024-01-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('rarity', models.CharField(choices=[('highrare', '最上級'), ('rare', '上級'), ('common', '中級')], max_length=100)),
            ],
        ),
    ]
