# Generated by Django 4.1.3 on 2024-01-05 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('composite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('item', models.ForeignKey(limit_choices_to={'name__in': ()}, on_delete=django.db.models.deletion.CASCADE, related_name='composite_items', to='composite.item')),
                ('material', models.ForeignKey(limit_choices_to={'name__in': ()}, on_delete=django.db.models.deletion.CASCADE, related_name='composite_materials', to='composite.item')),
            ],
        ),
    ]
