# Generated by Django 4.1.3 on 2024-01-05 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('composite', '0002_composite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.AlterField(
            model_name='composite',
            name='item',
            field=models.ForeignKey(limit_choices_to={'name__in': ({'name': '中級源岩'}, {'name': '上級源岩'}, {'name': '中級異鉄'}, {'name': '上級異鉄'}, {'name': '中級装置'}, {'name': '上級装置'}, {'name': '中級エステル'}, {'name': '上級エステル'}, {'name': '中級アケトン'}, {'name': '上級アケトン'}, {'name': '中級糖原'}, {'name': '上級糖原'}, {'name': 'マンガン'}, {'name': '上級マンガン'}, {'name': '融合剤'})}, on_delete=django.db.models.deletion.CASCADE, related_name='composite_items', to='composite.item'),
        ),
        migrations.AlterField(
            model_name='composite',
            name='material',
            field=models.ForeignKey(limit_choices_to={'name__in': ({'name': '中級源岩'}, {'name': '上級源岩'}, {'name': '中級異鉄'}, {'name': '上級異鉄'}, {'name': '中級装置'}, {'name': '上級装置'}, {'name': '中級エステル'}, {'name': '上級エステル'}, {'name': '中級アケトン'}, {'name': '上級アケトン'}, {'name': '中級糖原'}, {'name': '上級糖原'}, {'name': 'マンガン'}, {'name': '上級マンガン'}, {'name': '融合剤'})}, on_delete=django.db.models.deletion.CASCADE, related_name='composite_materials', to='composite.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
