# Generated by Django 4.1.3 on 2024-01-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composite', '0004_alter_composite_item_alter_composite_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
