# Generated by Django 4.1.3 on 2024-01-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composite', '0005_item_id_alter_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rarity',
            field=models.CharField(choices=[('最上級', '最上級'), ('上級', '上級'), ('中級', '中級')], max_length=100),
        ),
    ]
