# Generated by Django 4.1.3 on 2024-01-08 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('composite', '0006_alter_item_rarity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comp_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_quantity', models.PositiveIntegerField()),
                ('comp_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composite_composites', to='composite.item')),
            ],
        ),
    ]
