# Generated by Django 4.1.3 on 2024-01-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composite', '0007_comp_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp_list',
            name='comp_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='composite',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
